--DROP USER ADMIN
ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;
REVOKE SYSDBA FROM USER_ADMIN;
DROP USER USER_ADMIN CASCADE;
--DROP CAC PROCEDURE TUONG UNG
DROP PROCEDURE GET_ALL_USERS;
DROP PROCEDURE GET_ALL_ROLES;
DROP PROCEDURE GET_ALL_PRIVS;
DROP PROCEDURE CHECK_PRIVIS_A_ACTOR;
DROP PROCEDURE CREATE_USER;
DROP PROCEDURE CREATE_ROLE;
DROP PROCEDURE Sp_Grant_Permission_To_User_Or_Role;
DROP PROCEDURE Sp_Grant_Role_To_User;
DROP PROCEDURE ChangeUserPassword;
DROP PROCEDURE ChangeRolePassword;
DROP PROCEDURE DROP_USER;
DROP PROCEDURE DROP_ROLE;
DROP PROCEDURE GRANT_PRIVILEGES;
DROP PROCEDURE GRANT_ADMIN_OPTION;
DROP PROCEDURE REVOKE_PRIVILEGES;
DROP PROCEDURE Sp_RevokePrivilegeOnTable;
DROP PROCEDURE REVOKE_ADMIN_OPTION;